FindLibKrb5.cmake

Related to this: https://github.com/bro/bro/pull/131

Add FindLibKrb5 module

---

BifCl.cmake
BroPluginDynamic.cmake

Changed ".bro" file extension to ".zeek".

Change ".bro" script file extension to ".zeek"

---

FindKqueue.cmake

Part of https://github.com/zeek/zeek/pull/681, which is linked to https://github.com/zeek/zeek/issues/264

Add FindKqueue script for managing libkqueue

---

RequireCXX17.cmake
SetDefaultCompileFlags.cmake

This set of changes is requires for porting Broker to MSVC.

Add MSVC branches to compiler and flag setups

---

FindKqueue.cmake
ZeekPluginDynamic.cmake

Part of https://github.com/zeek/zeek/pull/848

Update libkqueue/rapidjson include paths

---

InstallSymlink.cmake

With binary packaging, this moves the symlink creation from configuration to
installation, uses an alternative name for the symlink created in the build
directory prior to installation, and removes this link after installation to
avoid dangling links.
This fixes two problems: (1) the early symlink creation could interfere with
supposedly local operations on the file, for example creating a symlink to
itself, (2) leaving behind symlinks into the build tree after one install could
trip up subsequent configure/build runs because again operations intended to be
local ended up in the build tree, which might not be writable or not exist at
all.
Resolves zeek/zeek#1702, resolves zeek/zeek#1703.

Fix link handling with binary packaging in InstallSymlink

---

BuiltInSpicyAnalyzer.cmake

Goes with https://github.com/zeek/zeek/pull/2651.

Provide infrastructure to migrate legacy analyzers to Spicy inside the Zeek tree.

---

zeek-plugin-create-package.sh

Prevent build interference from creating dist tarball

---

BifCl.cmake
BinPAC.cmake
BuiltInSpicyAnalyzer.cmake
FindCAres.cmake
Gen-ZAM.cmake
ZeekPlugin.cmake
ZeekPluginCommon.cmake
ZeekPluginDynamic.cmake
ZeekPluginStatic.cmake

This is the `cmake`-submodule side of https://github.com/zeek/zeek/pull/2710.
Feedback is most welcome, but the work isn't done yet. There are still a couple of rough edges here plus the dynamic plugins are broken at the moment (working on it).

Modernize and simplify CMake scaffolding

---

BinPAC.cmake
FindBinPAC.cmake
ZeekPlugin.cmake
ZeekPluginDynamic.cmake

Companion PR for https://github.com/zeek/zeek/pull/2954.

Add bootstrapping for plugins that use zeek-config

---

ZeekPluginStatic.cmake

Companion PR for https://github.com/zeek/zeek/pull/2972.

Set ZEEK_CONFIG_SKIP_VERSION_H for static plugins

---

BuiltInSpicyAnalyzer.cmake
FindSpicy.cmake
FindZeek.cmake
ZeekSpicyAnalyzerSupport.cmake

This goes with https://github.com/zeek/zeek/pull/2996.

Support the integration of the Spicy plugin code into Zeek proper.

---

ZeekPlugin.cmake

Companion PR for https://github.com/zeek/zeek/pull/2979.

Allow plugins to call find_package(Zeek)

---

BuiltInSpicyAnalyzer.cmake
ZeekPluginCommon.cmake
ZeekPluginDynamic.cmake
ZeekPluginStatic.cmake

This is the cmake changes for https://github.com/zeek/zeek/pull/3124

Force -std=c++17 compiler argument for plugin targets

---

BuiltInSpicyAnalyzer.cmake

Prefer Spicy include directories of this build over accidental ones.

---

BuiltInSpicyAnalyzer.cmake

Install grammars of builtin Spicy analyzers.

---

FindKqueue.cmake

FindKqueue: Do not modify global include dirs

---

ZeekPluginStatic.cmake

This PR corresponds to https://github.com/zeek/zeek/pull/3528

Pass -Werror in static plugin builds

---

CheckCompilers.cmake

Fixes https://github.com/zeek/zeek/issues/3754

Throw an error if any compiler except MSCV is used on Windows

---

RequireCXX17.cmake

Fixes https://github.com/zeek/cmake/issues/81
See https://cirrus-ci.com/build/6198958445297664 for CI testing

Update required compiler versions to match Zeek documentation

---

ZeekPluginStatic.cmake

This requires https://github.com/zeek/zeek/pull/4366 to be merged

Add clang-tidy and iwyu to plugin targets

---

FindLibKrb5.cmake

For https://github.com/zeek/zeek/pull/4456

Prefer libkrb5 from Homebrew over macOS system version
