- FindPythonDev.cmake
Since Python under version 3.4 is now out of lifecycle and Python 3.8 not released yet, only Python 3.4-3.7 added.
> Search for `python-config` from Python 3 as well.

- BifCl.cmake
- BinPAC.cmake
- FindClangTidy.cmake
- ZeekPluginCommon.cmake
- ZeekSubdir.cmake
This adds some common functions to help with extending the current Zeek clang-tidy support and make it more generic.
> Add FindClangTidy to make the invocation of clang-tidy more generic

- FindBroker.cmake
- FindCAF.cmake
These changes allow users to use a build directory for `CAF_ROOT` and `BROKER_ROOT` respectively. This comes in very handy when constantly moving back-and-forth between code in CAF, Broker and Zeek.
> Update FindCAF and improve FindBroker

- RequireCXX17.cmake
As of CMake 3, we can safely assume that `CMAKE_CXX_COMPILER_VERSION` exists. Also, Apple uses different versions for its Clang version than the LLVM project. It seems like Apple Clang 6 is ≥ LLVM Clang 4.0: https://trac.macports.org/wiki/XcodeVersionInfo. With CMake 3, we can simply check this by asking for "AppleClang".
Also, the upstream projects Broker and Zeek both have a bug in their CMake setup: `cmake_minimum_required` must come *before* `project(...)` in order to get the correct policy setup: https://gitlab.kitware.com/cmake/cmake/issues/19067. I'll file separate PRs for that.
> Fix AppleClang version check, remove obsolete code

- RequireCXX17.cmake
Clang 4 [doesn't implement the `-std=c++17` flag](https://clang.llvm.org/cxx_status.html):
> use `-std=c++1z` in Clang 4 and earlier
> Use c++1z flag on Clang 4.0 for C++17

- ZeekPluginStatic.cmake
- ZeekSubdir.cmake
With CMake 3 as build dependency, we no longer need to use the static library workaround for old CMake versions introduced via https://github.com/zeek/zeek/commit/8e7ef001b3a07cba186c8476ba044230aeb9b7aa and instead can use CMake's object libraries.
This change breaks Zeek `master` (see accompanying PR in `zeek/zeek` for the required Zeek-side changes).
> Use object libraries for subdir libs and plugins

- RequireCXX17.cmake
Currently, we first unconditionally add a C++17 flag and then try to compile. If a user (or parent project) already provides CXX flags that select a suitable C++ version, we should make sure not to "downgrade"
the selected standard (for example if the user selects C++20). Hence, we first check whether C++17 is already enabled before modifying the flags and trying again.
> Check for C++17 before adding flags

- SetDefaultCompileFlags.cmake
Related to https://github.com/zeek/zeek/issues/895
> Use -Werror=vla to prevent use of Variable-Length-Array in C++

- FindCAF.cmake
When setting `CAF_ROOT` to a build CAF directory, Zeek/Broker won't find 0.18 headers and libs any more. This PR adds additional search paths to allow the script to work with the upcoming CAF release as well.
> Update FindCAF for 0.18 file locations

- InstallPackageConfigFile.cmake
InstallPackageConfigFile generates a target name from a file name,
replacing "/" with "." since "/" isn't allowed in a target name.
However, other characters that appear in file names are't allowed in
target names, notably the Windows volume separator, ":".  Address that
by replacing all characters except those explicitly allowed in a target
name according to CMP0037.
This is part of zeek/zeek#951.
> InstallPackageConfigFile: replace disallowed chars in target name

- ZeekPluginDynamic.cmake
Addresses https://github.com/zeek/zeek/issues/1180
This helps ensure successful compilation of a plugin that includes a
Zeek header which includes an external dependency header even if the
plugin itself doesn't necessarily depend on that external library.
> Add external Zeek dependency headers to plugin include paths

- ZeekPluginDynamic.cmake
The custom command for binary install packages declares an `OUTPUT`
that it produced `${plugin_name_canon}.tar.gz` in the current bin dir.
This was not correct as `zeek-plugin-create-package.sh` produces a
`tar.gz` file in the `dist` subdirectory which it symlinks into the
current bin dir as `tgz`. Due to that the output of the command was
never present and the `dist` was always run.
This patch fixes this by changing the custom command to declare that it
creates the file in the current bin directory (the `tgz` file). With
that the rule producing the file is only rerun if the inputs of the
custom command become outdated.
> Set correct OUTPUT for binary install package.

- ZeekPluginDynamic.cmake
Since the FindCAF.cmake was previously removed, this change allows for
finding the CAFConfig.cmake of the associated CAF installation that Zeek
is built against, restoring the find_package(CAF ...) functionality.
Addresses https://github.com/zeek/zeek/issues/1347
> Fix ZeekPluginDynamic's ability to find CAF package config file

- OpenSSLTests.cmake
This detects if `<openssl/kdf.h>` is available in the build. We use this in https://github.com/zeek/zeek/pull/1518 (transparent TLS decryption) to selectively enable TLS key derivation based on the API in this header.
@0xxon this change should be easy to land right?
EDIT: Also `check_include_file` would have been enough here as we only care about a single header, but as `check_include_files` was used in other places, I opted for this instead.
> OpenSSLTests.cmake: check for <openssl/kdf.h>

- CheckFunctions.cmake
glibc 2.33 deprecates mallinfo() because the returned sizes are ints. mallinfo2() upgrades these to size_ts.
> Add check for mallinfo2()

- ConfigurePackaging.cmake
> When building dynamic plugins, omit additional paths from RPM

- ZeekPluginCommon.cmake
- ZeekPluginDynamic.cmake
[Zeek/Zeek Issue #1848](https://github.com/zeek/zeek/issues/1848)
Add new function zeek_plugin_script().
Script files added through this function will be added as dependencies
to the binary package, and changes to the script will be picked up
by `make && sudo make install` without a `make clean` being required.
Scripts that are *not* added through this command will still be
distributed as before, but a change to the script will require
a `make clean` ( as before ) in order to trigger repackaging if
there is no change that triggers the plugin's not script components
to build.
Follow ons to this are updating the zeek reference, adding init-plugin
support and any doc changes
> new zeek_plugin_script() function to allow distribution build dependency on script changes

- ZeekPluginCommon.cmake
- ZeekPluginDynamic.cmake
This expands the zeek plugin cmake functions/macros to support CTest and unit testing via doctest.  The gist is that support for unit testing is transparently available when Zeek offers it, gets disabled when Zeek doesn't offer it, and the user can additionally opt to suppress unit test compilation despite Zeek offering it.
Part of zeek/zeek#1661.
> Unit test support for plugins

- FindOpenSSL.cmake
This fixes a couple of bugs, specifically dealing with lib64 (which bit me in the past), plus one version comparison.
> Pull updated version of FindOpenSSL from cmake

- ZeekPluginDynamic.cmake
With the removal of the public CAF dependency it appears we also need to remove looking for CAF from ZeekPluginDynamic.cmake.
I also noticed that zeek-config still has a "--caf_root" option, but I don't know what downstream effects removing it may have.
> Remove the search for CAF from ZeekPluginDynamic.cmake

- Gen-ZAM.cmake
This provides a gen_zam_target macro to manage invocation of Gen-ZAM, collection of output files (in GEN_ZAM_OUTPUT_H), and creation of a target. An existing executable can be provided via GEN_ZAM_EXE_PATH, and is otherwise located locally.
Modeled on BifCl.cmake.
This is a companion PR to zeek/zeek#1989.
> Add cmake module for invoking Gen-ZAM

- MacDependencyPaths.cmake
This is two changes:
- Now that we're requiring cmake 3.15, we can use `list(PREPEND)` instead of inserting at the front
- We already had code in `MacDependencyPaths.cmake` to use the alternate path for bison when looking for dependencies, but we didn't for flex. This adds that path, which allows cmake to find the include files and such instead of needing to manually specify the path.
> Fix CMake finding Flex installed via Homebrew

- FindClangTidy.cmake
This small change fixes the check for the `run-clang-tidy` script to also attempt to find the version without `.py`, which is what is provided by llvm distributions now.
> Fix check for run-clang-tidy

- ZeekPluginCommon.cmake
This took me a bit to figure out: since `zeek_plugin_end` is a macro, setting the policy in `ZeekPluginCommon.cmake` only takes effect when done inside the macro, not higher up in the file. Two related things to flag:
- Should we additionally wrap the policy adjustment in its own `cmake_policy(PUSH)` / `cmake_policy(POP)`?
- Reading up about cmake policies, it seems like the preferred way to set them (if you need to set them at all) is at the project toplevel, but this is a plugin setting, so this code will also run for external plugins, Zeek packages with plugins, etc. It seems okay to me to set this policy for all users, but one could also argue that we're not in charge of the policies of any Zeek plugin out there.
@Neverlord let me know in case this clashes with any cmake cleanups …
> Set CMP0110 to new in the plugin code to permit whitespace in test names

- PCAPTests.cmake
`DLT_LINUX_SLL` and `DLT_LINUX_SLL2` are libpcap link-types for fake link-layer headers used when capturing packets on Linux with `PF_PACKET` (which happens if you run `tcpdump -i any`).
The difference between the versions is a slightly modified header/struct and link-type number. Zeek currently understands version 1. I'm working on https://github.com/zeek/zeek/pull/2340 which adds support for reading version 2 PCAP files.
Libpcap only added `DLT_LINUX_SLL2` support in version 1.10.0. 
On @timwoj's suggestion, this PR has `DONT_HAVE_LIBPCAP_DLT_LINUX_SLL2` set by cmake allows for conditionally compiling in a check/abort when trying to read this type of file with an older libpcap (i.e., Ubuntu <= 18, Debian <= 10, Centos <= 7). The `btest` case added in …
> Set DONT_HAVE_LIBPCAP_DLT_LINUX_SLL2 if libpcap doesn't have LINUX_SLL2 support

- BinPAC.cmake
- BroPlugin.cmake
When including icsnpp-bacnet via --include-plugins, binpac failed to compile the bacnet.pac file as it didn't find the zeek/binpac.pac due to Zeek's src path not being included.
With this change, external builtin-plugins have -I flags added for their binpac invocation.
> BinPAC: Allow external builtin-plugins to find .pac files from Zeek's tree

- ZeekPluginCommon.cmake
- ZeekPluginStatic.cmake
* Track libraries to link in new `bro_PLUGIN_LINK_LIBS` variable
* Unconditionally use include_directories for source/binary dir in `zeek_plugin_begin()`
Relates to zeek/zeek#2482 zeek/zeek#2520
> Plugins: Modification for included plugins

- zeek-plugin-create-package.sh
During #61, the symbolic link dereferencing that was done when creating the manifest was disregarded. The current version packages up symlinks to directories.
Found by @dopheide-esnet, thanks!
> zeek-plugin-create-package: Dereference symbolic links during cp

- BinPAC.cmake
We've removed the zeek -> . symlink from zeek/src and now create
it dynamically during the build in zeek/src/include. Ensure that
new directory is in BinPAC's include path, too.
Fixes --include-plugins with plugins that contain BinPAC based analyzers
and using `%include zeek/binpac.pac` as, for example, this one:
https://github.com/cisagov/icsnpp-bacnet.git
> BinPAC: Ensure zeek/src/include is added to BinPAC include path

- ConfigureSpicyBuild.cmake
Add helper script to adapt Spicy build inside Zeek.
This goes with https://github.com/zeek/zeek/pull/3041.
This is on top of `topic/robin/spicy-plugin`, only the 2nd commit is new in this PR.
> Move Spicy up a level

- ZeekSpicyAnalyzerSupport.cmake
When a zkg package brought multiple independent Spicy analyzers, their
build would break because our CMake logic would attempt to create a
symbolic link multiple times; which would fail for all but the 1st
analyzer, aborting their builds. This change moves creation of the
link out of the build commands.
> Fix build of multiple Spicy analyzers in a package.

- BuiltInSpicyAnalyzer.cmake
- ZeekSpicyAnalyzerSupport.cmake
This patch disables LSAN for invocations of `spicyz` when building builtin or external Spicy analyzers. ASAN automatically enables LSAN, even on platforms where it is unsupported (e.g., macOS), so we disable it again for this use case.
Closes zeek/zeek#3026.
> Disable LSAN when running spicyz during analyzer build.

- ZeekPluginDynamic.cmake
zkg's tests failed with current master due to the newline not being in the magic plugin file anymore.
Keep it for consistency so we don't need to play tricks to normalize the baselines across versions.
> ZeekPluginDynamic: Add back newline in magic file

- ZeekPluginDynamic.cmake
`DIST_FILES` isn't set when we add the custom command. Use the variable from the call to `cmake_parse_arguments` instead.
Fixes https://github.com/zeek/zeek/issues/3107
From a simple test plugin generated by `init-plugin` with no other changes:
```
tim@coregeek2 build% tar -tzf dist/Test_TestPlugin-0.1.0.tar.gz                                      [master]
Test_TestPlugin/
Test_TestPlugin/__bro_plugin__
Test_TestPlugin/CHANGES
Test_TestPlugin/README
Test_TestPlugin/VERSION
Test_TestPlugin/scripts/
Test_TestPlugin/lib/
Test_TestPlugin/lib/bif/
Test_TestPlugin/lib/Test-TestPlugin.darwin-arm64.so
Test_TestPlugin/lib/bif/testplugin.bif.zeek
Test_TestPlugin/lib/bif/__load__.zeek
Test_TestPlugin/scripts/Test/
Test_TestPlugin/scripts/__load__.zeek
Test_TestPlugin/scripts/__preload__.zeek …
```
> Ensure that dist files are included in plugin tarballs

- ZeekPlugin.cmake
- ZeekPluginCommon.cmake
- ZeekPluginDynamic.cmake
- ZeekPluginStatic.cmake
This adds the old zeek_plugin_scripts() mechanism to the new zeek_add_plugin() function such that upon modification of the listed script files the tarball is re-created.
Closes #75
> ZeekPlugin: Add SCRIPT_FILES argument

- ZeekPlugin.cmake
set() for CMAKE_BUILD_TYPE has no effect without force even if empty, do a conditional set(...FORCE) instead.
> ZeekPlugin: Fixup CMAKE_BUILD_TYPE setting

- zeek-plugin-create-package.sh
Doing `./configure && make && make install` on a plugin throws the following errors on macos:
```
$ ./configure && make && make install
...
make: [build-it] Error 1 (ignored)
( cd build && make )
...
[100%] Building binary plugin package: /Users/yacin.nadji/src/VantageTime/build/Corelight_VantageTime.tgz
cp: the -H, -L, and -P options may not be specified with the -r option.
[100%] Built target Corelight_VantageTime_tarball
```
This results in a largely empty plugin tarball to be installed. Digging into this further, we see it's from:
```
$ bash -x /Users/yacin.nadji/zeek/share/zeek/cmake/zeek-plugin-create-package.sh Corelight_VantageTime
+ '[' 1 = 0 ']'
+ name=Corelight_VantageTime
+ shift
+ addl=
+ DIST=dist/Corelight_VantageTime
+ mkdir -p dist/Corelight_VantageTime
+ cp -rL …
```
> use -R for macos compatibility

- FindSpicy.cmake
When searching for `spicy-config` we previously we would pass configured paths as `HINTS` to `find_program`. Since `HINTS` adds additional search paths to builtin search paths, this did not find the correct `spicy-config` if Zeek was configured with `--with-spicy=<SPICY_PREFIX>` and another `spicy-config` was found in builtin paths; instead we would always prefer to use the one from builtin paths.
With this patch we split the search for `spicy-config` into two phases, one using exclusively the configured paths and only if that search did not succeed a second phase which would look in builtin paths. With that we prefer a `spicy-config` from an explicitly configured path.
> Prefer to find `spicy-config` in configured over default search paths.

- OpenSSLTests.cmake
The only place NEED_KRB5_H was referenced on the Zeek side didn't seem to have any effect and so it was dropped. Remove the check and extra logic for /usr/kerberos/include assuming the Red Hat distro mentioned in the comment is long out of support.
> OpenSSLTests: Remove krb5.h include test

- ZeekSpicyAnalyzerSupport.cmake
This adds a named arg `ENV` to `spicy_add_analyzer` which accepts values `VAR=VAL` which get injected into the generated `spicyz` invocation. This makes it possible to e.g., parameterize values like `HILTI_CXX_INCLUDE_DIRS`.
> Allow injecting env vars into `spicyz` invocation in `spicy_add_analyzers`

- BuiltInSpicyAnalyzer.cmake
This is needed to integrate spicy-ldap into Zeek, zeek/zeek#3305.
> Add support for builtin Spicy analyzers with more than one module

- BuiltInSpicyAnalyzer.cmake
For external packages, spicy_add_analyzer() supports .cc files given to SOURCES. Add the same capability to the spicy_add_analyzer() function provided by BuiltInSpicyAnalyzer().
The spicy-quic analyzer has an extra .cc file.
> BuiltinSpicyAnalyzer: Support CXX files for SOURCES

- ZeekPlugin.cmake
The warning is useful, but usually scrolls off the screen before users
run into errors that are less actionable. We now had 3 reports of users
that were stuck with less useful message around the IN_LIST operator
when all they had to do was but the cmake_minimum_required() line.
> ZeekPlugin: Make non-sufficient minimum version a FATAL_ERROR

- ZeekPlugin.cmake
I think I tried to protect against `ZEEK_DIST` not being a cache variable and to avoid FORCE-setting a bunch of cache variables each run. The latter would mean user-made changes to the cache file are overridden each time. However, after going through the function, I think touching any of those variables is a bad idea anyways. So we can just not do the caching.
Worked locally for me (forcing CMake to re-run by touching the CMakeLists.txt file in a plugin). But any more testing is most welcome.
Closes #76.
> Remove overly cautious caching

- ZeekPluginDynamic.cmake
- ZeekPluginStatic.cmake
INCLUDE_DIRS is allowed for zeek_add_plugin(), but it has not been threaded through to the target.
Relates to zeek/zeek#3420.
> zeek_add_plugin: Fix INCLUDE_DIRS

- ZeekSpicyAnalyzerSupport.cmake
In the spicy-quic project it was found that the quic.hlto wasn't being rebuilt/relinked when the libdecrypt_crypto.a library changed. @bbannier hinted at a missing dependency on the CXX_LINK argument for the custom command invoking spicyz.
> spicy_add_analyzer: Depend on CXX_LINK arg

- BuiltInSpicyAnalyzer.cmake
> Fix Spicy include flags for externally built Spicy.

- Gen-ZAM.cmake
This PR is a companion to one I'm about to put in for Zeek to enable `gen-zam` to take multiple arguments. The Zeek PR doesn't actually leverage this capability yet (but I'll start working on a branch that does once https://github.com/zeek/gen-zam/pull/13 is merged).
> configuration hooks to enable gen-zam to take multiple arguments

- SetDefaultCompileFlags.cmake
Instead of setting `CMAKE_*_FLAGS` directly, set `EXTRA_COMPILE_FLAGS` like everything else in this file and let them get added to the CMAKE flags at the end.
Related to https://github.com/zeek/zeek/pull/3748
> Use EXTRA_COMPILE_FLAGS for coverage flag

- FindPrometheusCpp.cmake
Related to https://github.com/zeek/zeek/pull/3701
> Add FindPrometheusCpp file for prometheus-cpp library

- FindPrometheusCpp.cmake
The old code overwrote CFLAGS/CXXFLAGS entirely, which removed all of the flags needed for some of the binary builds. This ensures that those flags persist, minus the one flag that was causing problems with civetweb.
Fixes https://github.com/zeek/zeek/issues/3764
> Don't overwrite all of CFLAGS/CXXFLAGS in prometheus-cpp build

- SetDefaultCompileFlags.cmake
Running lcov on Ubuntu 24.04 on a coverage enabled build by hand produces the following error on Ubuntu 24.04:
lcov --no-external --capture --directory . --output-file coverage.info
Processing ./build/auxil/broker/caf/libcaf_core/CMakeFiles/libcaf_core_obj.dir/src/actor_system.cpp.gcda
geninfo: ERROR: Unexpected negative count '-1' for /zeek/auxil/broker/caf/libcaf_core/src/actor_system.cpp:503.
Perhaps you need to compile with '-fprofile-update=atomic
(use "geninfo --ignore-errors negative ..." to bypass this error)
Compile with -fprofile-update=atomic for coverage enabled builds.
> Compile coverage builds with -fprofile-update=atomic

- ZeekPluginDynamic.cmake
- zeek-plugin-create-package.sh
Move path wrangling of DIST files from zeek-plugin-create-package.sh into CMake logic.
New logic: Relative paths have all leading ../ components strip to determine the location within the resulting tarball. This also removes the assumption of having build/ located within the source directory (and zeek-plugin-create-package.sh running from build/).
The quirky part is that the script deletes the produced files after creating the tarball.
> ZeekPluginDynamic: Handle DIST_FILES in CMake

- ZeekBundle.cmake
This is exactly @Neverlord's #115, without the removal of `FindPrometheus.cmake` and with a bit of context in the commit message since development of `ZeekBundle.cmake` happened in Dominik's Broker branch before moving over here.
> Add ZeekBundle for integrating third-party components into our builds

- ZeekBundle.cmake
This is a band-aid fix. Ideally, we shouldn't be using `FetchContent_Populate` since it's been deprectated, and should be instead using a combination of `FetchContent_Declare` and `FetchContent_MakeAvailable`.
> Workaround for configure failures with FETCHCONTENT_FULLY_DISCONNECTED

- ZeekSpicyAnalyzerSupport.cmake
We use the `SPICY` variable to consistently reference the `spicyz` executable to use. This patch fixes a few more instances where we still referenced it directly.
> [PATCH] Consistently use `SPICY` to refer to `spicyz` executable

- FindCAres.cmake
- FindKqueue.cmake
I noticed this while adding Redis support to the storage framework branch. We can't hardcode `.so`/`.a` for all platforms because on Windows it's `.dll`/`.lib` and on macOS shared libraries are `.dylib`. Use CMake variables to make these checks platform-independent.
> Use CMake variables for shared/static library suffixes

- FindLibKrb5.cmake
This came up while fixing https://github.com/zeek/zeek/pull/4359, where searching for krb5.h on macOS defaults to the system library even if `--with-krb5` is passed to `configure`.
> Fix some issues with finding libkrb5 and krb5.h

- FindLibKrb5.cmake
The version of libkrb5 that comes with macOS is quite old and has problems that cause Zeek's btests to fail. Instead of blindly using it, report an error and tell the user to use the version from Homebrew. That version is known to work.
> Report FATAL_ERROR for macOS system libkrb5

- ConfigureSpicyBuild.cmake
auxil/spicy or more correctly its dependency justrx emitted its test targets into the build and we reconfigured them. Since we will not build these targets going forward and they will actually be unknown remove their configuration.
> Do not tweak test targets from Spicy

- ZeekPluginStatic.cmake
This changes the include style for directories outside of the current project tree to use `-isystem` instead of `-I`. This allows clang-tidy to ignore those files with the `SystemHeaders: false` configuration option. I only made this change for static plugins, since we probably won't be running clang-tidy with dynamic plugins.
> Add external directories included by plugins as system directories

- FindPrometheusCpp.cmake
A couple of the static binary builds started failing recently due to duplicate Civetweb/Prometheus-cpp symbols. We statically link these symbols into libbroker during build, and then attempt to link them again while linking Zeek. It's strange that this hasn't come up before, but it's possible that a recent compiler upgrade became more strict about it. Stop linking them into Zeek and use the symbols from Broker. If we ever remove Broker, this line can be uncommented again.
Related to https://github.com/zeek/zeek/issues/4732
> Link Prometheus symbols via Broker instead of directly
